# Model arguments
model_name_or_path: chargoddard/Yi-6B-Llama
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
dataset_mixer:
  amazingvince/sft-max-2: 1.0
dataset_splits: 
- train
- test
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: "steps"
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
hub_model_id: where-lambo-7b-sft-full
hub_strategy: every_save
learning_rate: 2.0e-05
neftune_noise_alpha: 5
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 4096
max_steps: -1
num_train_epochs: 1
output_dir: ~/usr/bin/nvidia-smi/data/where-lambo-sft-full
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: true
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: "steps"
save_steps: 200
save_total_limit: 1
seed: 42
tf32: true