# Model arguments
model_name_or_path: mistralai/Mistral-7B-v0.1
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
dataset_mixer:
  amazingvince/sft-max-2.1: 1.0
dataset_splits: 
- train
- test
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: "steps"
eval_steps: 400
gradient_accumulation_steps: 16
gradient_checkpointing: true
hub_model_id: where-llambo-sft-full
hub_strategy: every_save
# optim: adamw_torch_fused
learning_rate: 2.0e-06
# adam_beta1: 0.90
# adam_beta2: 0.95 
# adam_epsilon: 1.0e-6 
warmup_ratio: 0.01
weight_decay: 1.0e-04
lr_scheduler_type: cosine
neftune_noise_alpha: 5
torch_compile_backend: inductor
torch_compile: true
torch_compile_mode: max-autotune
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 4096
max_steps: -1
num_train_epochs: 1
output_dir: data/where-llambo-sft-full
overwrite_output_dir: true
per_device_eval_batch_size: 3
per_device_train_batch_size: 3
push_to_hub: true
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: "steps"
save_steps: 200
save_total_limit: 1
seed: 42
tf32: true